version: "3.3"

services:
  db:
    image: mariadb
    container_name: mariadb-www
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    command: --sql_mode=""
    networks:
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: netedit2
      MYSQL_USER: netedit2
      MYSQL_PASSWORD: netedit2

  www:
    build: .
    container_name: www
    ports:
      - "8001:80"
    volumes:
      - ./www:/var/www/html/
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    links:
      - db
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-www
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: somewordpress
      UPLOAD_LIMIT: 1024M
      MEMORY_LIMIT: 1024M
volumes:
  persistent:
