version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    command: --sql_mode=""
    networks:
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: netedit2
      MYSQL_USER: netedit2
      MYSQL_PASSWORD: netedit2

  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
    links:
      - db
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: somewordpress
      UPLOAD_LIMIT: 300M
volumes:
  persistent:
